server:
  port: ${config.port:8081}
spring:
  application:
    name: server-config
  # 定义config使用jdbc模式
  profiles:
    active: jdbc
  # 定义数据源
  datasource:
  password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host:43.142.129.223}:${db.port:3307}/wechat-mysql?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  # 配置从数据库中获取配置属性

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8080}/eureka
instance:
  prefer-ip-address: true
  ip-address: ${config.ip:127.0.0.1}